import { Router, type IRouter } from "express";
import healthRouter from "./health.js";
import authRouter from "./auth.js";
import googleAuthRouter from "./auth-google.js";
import webhooksRouter from "./webhooks.js";
import dashboardRouter from "./dashboard.js";
import propertiesRouter from "./properties.js";
import roomsRouter from "./rooms.js";
import bookingsRouter from "./bookings.js";
import residentsRouter from "./residents.js";
import complaintsRouter, { escalationsRouter } from "./complaints.js";
import { employeeRouter, attendanceRouter, leavesRouter, recruitmentRouter } from "./employees.js";
import { procurementRouter, vendorRouter, indentRouter, poRouter, grnRouter, inventoryRouter } from "./procurement.js";
import { recipesRouter, menuPlansRouter, productionRouter, kitchenAnalyticsRouter } from "./kitchen.js";
import { leadsRouter, propertyLeadsRouter } from "./sales.js";
import { coursesRouter, enrollmentsRouter } from "./lnd.js";
import { usersRouter, announcementsRouter } from "./users.js";
import laundryRouter from "./laundry.js";
import { templatesRouter, commsRouter } from "./communications.js";
import { notificationsRouter } from "./notifications.js";
import { pushRouter } from "./push.js";
import { executiveRouter } from "./executive.js";
import { settingsRouter } from "./settings.js";
import { kycRouter, esignRouter, esignPublicRouter } from "./kyc-esign.js";
import { financeRouter } from "./finance.js";
import { facilityRouter, electricityRouter, residentAttendanceRouter, outPassRouter, iotRouter, iotIngestionRouter } from "./operations.js";
import { walletRouter } from "./wallet.js";
import foodRouter from "./food.js";
import foodOpsRouter from "./food-ops.js";
import geocodeRouter from "./geocode.js";
import bulkRouter from "./bulk.js";

const router: IRouter = Router();

router.use(healthRouter);
router.use("/auth", authRouter);
router.use("/auth", googleAuthRouter);
router.use(webhooksRouter);
router.use("/dashboard", dashboardRouter);
router.use("/properties", propertiesRouter);
router.use("/rooms", roomsRouter);
router.use("/bookings", bookingsRouter);
router.use("/residents", residentsRouter);
router.use("/complaints", complaintsRouter);
router.use("/escalations", escalationsRouter);
router.use("/employees", employeeRouter);
router.use("/attendance", attendanceRouter);
router.use("/leaves", leavesRouter);
router.use(recruitmentRouter);
router.use("/procurement", procurementRouter);
router.use("/vendors", vendorRouter);
router.use("/indents", indentRouter);
router.use("/purchase-orders", poRouter);
router.use("/grn", grnRouter);
router.use("/inventory", inventoryRouter);
router.use("/recipes", recipesRouter);
router.use("/menu-plans", menuPlansRouter);
router.use("/daily-production", productionRouter);
router.use("/kitchen-analytics", kitchenAnalyticsRouter);
router.use("/leads", leadsRouter);
router.use("/property-leads", propertyLeadsRouter);
router.use("/courses", coursesRouter);
router.use("/enrollments", enrollmentsRouter);
router.use("/users", usersRouter);
router.use("/announcements", announcementsRouter);
router.use("/laundry", laundryRouter);
router.use("/message-templates", templatesRouter);
router.use("/communications", commsRouter);
router.use("/notifications", notificationsRouter);
router.use("/push", pushRouter);
router.use("/executive", executiveRouter);
router.use("/settings", settingsRouter);
router.use(kycRouter);
router.use(esignRouter);
router.use("/esign", esignPublicRouter);
router.use(financeRouter);
router.use("/facility", facilityRouter);
router.use("/electricity", electricityRouter);
router.use("/resident-attendance", residentAttendanceRouter);
router.use("/out-passes", outPassRouter);
router.use("/iot", iotRouter);
router.use("/iot", iotIngestionRouter);
router.use(walletRouter);
router.use("/food", foodRouter);
router.use("/food", foodOpsRouter);
router.use("/geocode", geocodeRouter);
router.use("/bulk", bulkRouter); // auth + authorize applied per-route inside

export default router;
